data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", stringsAsFactors = TRUE)
head(data)
str(data)
data$Date <- strptime(data$Date, "%d/%m/%Y")
select <- subset(data, Date >= "2007-02-01" & Date <= "2007-02-02")
select$Time <- paste(select$Date, select$Time)
select$Time <- strptime(select$Time, format = "%Y-%m-%d %H:%M:%S")
select$Date <- NULL

png(file = "plot4.png")
par(mfrow=c(2,2))
par(mar = c(3,4,5,2))
plot(select$Time, select$Global_active_power, type = "l", xlab = " ", ylab = "Global Active Power", cex.axis = 0.9, cex.lab = 0.9)
plot(select$Time, select$Voltage, type = "l", xlab = "datetime", ylab = "Voltage",  cex.axis = 0.9, cex.lab = 0.9)
plot(select$Time, select$Sub_metering_1, type = "l", xlab = " ", ylab = "Energy sub metering", col = "midnightblue",  cex.axis = 0.9, cex.lab = 0.9)
lines(select$Time, select$Sub_metering_2, col = "red")
lines(select$Time, select$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1,1,1), col = c("midnightblue", "red", "blue"), cex  = 0.9, bty = "n")
plot(select$Time, select$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power",  cex.axis = 0.9, cex.lab = 0.9)
dev.off()
